#mysql datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msg-center?characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: qw880712
  application:
    name: mcenter
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

server:
  port: 8888
  servlet:
    context-path: /menter

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://172.20.8.81:32190/eureka
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

hystrix:
  config:
    stream:
      maxConcurrentConnections: 20
  metrics:
    enabled: false

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000

eos:
  application:
    sys-code: CCMS
    sys-key: ab0975413cbb45d5ad54a1892ddf6fb0
    app-inst-grp-code: default
  springfox:
    enabled: false
  logging:
    outbound:
      enabled: false
      hh-enabled: false
    inbound:
      enabled: false
      hh-enabled: false
  accesscontrol:
    enabled: false
  webclient:
    enabled: false